const NOMOR_ANGGOTA = 'NOMOR_ANGGOTA';
const NAMA_ANGGOTA = 'NAMA_ANGGOTA';
const KODE_USER = 'KODE_USER';
const NIK = "NIK";
const NO_KTP = "NO_KTP";
const TGL_REGISTRASI = "TGL_REGISTRASI";
const PEKERJAAN = "PEKERJAAN";
const TEMPAT_LAHIR = "TEMPAT_LAHIR";
const TANGGAL_LAHIR = "TANGGAL_LAHIR";
const ALAMAT = "ALAMAT";
const NAMA_PERUSAHAAN = "NAMA_PERUSAHAAN";
const KODE_PERUSAHAAN = "KODE_PERUSAHAAN";
const EMAIL_PERUSAHAAN = "EMAIL_PERUSAHAAN";
const ALAMAT_PERUSAHAAN = "ALAMAT_PERUSAHAAN";
const LOKASI_PENEMPATAN = "LOKASI_PENEMPATAN";
const NAMA_KONFEDERENSI = "NAMA_KONFEDERENSI";
const CONTACT_ANGGOTA = 'CONTACT_ANGGOTA';
const IMG_PROFILE = 'IMAGE_PROFILE';

const JENIS_KELAMIN = 'JENIS_KELAMIN';
const STATUS = 'STATUS';
const KODE_JABATAN = 'KODE_JABATAN';
const NAMA_JABATAN = 'NAMA_JABATAN';
const KODE_BANK = 'KODE_BANK';
const NAMA_BANK = 'NAMA_BANK';
const CABANG_BANK = 'CABANG_BANK';
const NOMOR_REKENING = 'NOMOR_REKENING';
const PASSWORD = 'PASSWORD';
const STATUS_ANGGOTA = 'STATUS_ANGGOTA';
const ROLE = 'ROLE';
const EMAIL_PRIBADI = 'EMAIL_PRIBADI';
const NAMA_SAUDARA_DEKAT = 'NAMA_SAUDARA_DEKAT';
const HUBUNGAN_SAUDARA = 'HUBUNGAN_SAUDARA';
const ALAMAT_SAUDARA = 'ALAMAT_SAUDARA';
const NO_HP_SAUDARA = 'NO_HP_SAUDARA';
const PENDAPATAN = 'PENDAPATAN';
const SIMPANAN_WAJIB = 'SIMPANAN_WAJIB';
const SIMPANAN_SUKARELA = 'SIMPANAN_SUKARELA';
const JABATAN_KEANGGOTAAN = 'JABATAN_KEANGGOTAAN';
const STATUS_PERKAWINAN = 'STATUS_PERKAWINAN';
const KODE_FEDERASI = 'KODE_FEDERASI';


const JWT_TOKEN = 'JWT_TOKEN';

const DECRYPT_PASSWORD = 'DECRYPT_PASSWORD';